### ISSUE TITLE
Error when upgrading from 4.4.0 to 4.4.2 when using Lmod 6

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-framework#3888]
```
eb --install-latest-eb-release -l

(long, useless output which should not exist)
...
== 2021-10-17 15:15:30,403 environment.py:91 INFO Environment variable PATH set to /easybuild/2020/software/EasyBuild/4.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin (previous value: '/easybuild/2020/software/EasyBuild/4.4.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin')
== 2021-10-17 15:15:30,403 environment.py:91 INFO Environment variable MODULEPATH set to /easybuild/2020/modules/all:/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles (previous value: '/tmp/eb-iepw3rki/tmpvo5t4dhu/all:/easybuild/2020/modules/all:/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles')
== 2021-10-17 15:15:30,404 modules.py:464 INFO $MODULEPATH set via list of module paths (w/ 'module use'): /tmp/eb-iepw3rki/tmpvo5t4dhu/all:/easybuild/2020/modules/all:/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles
== 2021-10-17 15:15:30,475 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/2020/software/EasyBuild/4.4.0/lib/python3.8/site-packages/easybuild/base/exceptions.py:124 in __init__): Module command '/usr/share/lmod/lmod/libexec/lmod python --terse list' failed with exit code 1; stderr: Lmod has detected the following error: MODULEPATH has changed: run "module
update" to repair.



; stdout: false
 (at easybuild/2020/software/EasyBuild/4.4.0/lib/python3.8/site-packages/easybuild/tools/modules.py:830 in run_module)
== 2021-10-17 15:15:30,476 filetools.py:1876 INFO Removing lock /easybuild/2020/software/.locks/_easybuild_2020_software_EasyBuild_4.4.2.lock...
== 2021-10-17 15:15:30,477 filetools.py:358 INFO Path /easybuild/2020/software/.locks/_easybuild_2020_software_EasyBuild_4.4.2.lock successfully removed.
== 2021-10-17 15:15:30,477 filetools.py:1880 INFO Lock removed: /easybuild/2020/software/.locks/_easybuild_2020_software_EasyBuild_4.4.2.lock
== 2021-10-17 15:15:30,477 easyblock.py:3643 WARNING build failed (first 300 chars): Module command '/usr/share/lmod/lmod/libexec/lmod python --terse list' failed with exit code 1; stderr: Lmod has detected the following error: MODULEPATH has changed: run "module
update" to repair.
```

This is lmod 6, which

1) is default on debian AND ubuntu (and doesn't seem that it will change, so I would think about deprecating it)
2) should be working before in EasyBuild 4.x

`export LMOD_DISABLE_SAME_NAME_AUTOSWAP="no"` does not work (see https://github.com/easybuilders/easybuild/issues/710 )

The command itself works:

```
/usr/share/lmod/lmod/libexec/lmod python --terse list
os.environ["LMOD_DEFAULT_MODULEPATH"] = "/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles:/easybuild/2020/modules/all";
os.environ["MODULEPATH"] = "/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles:/easybuild/2020/modules/all";
EasyBuild/4.4.0
os.environ["LMOD_DEFAULT_MODULEPATH"] = "/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles:/easybuild/2020/modules/all";
os.environ["MODULEPATH"] = "/etc/lmod/modules:/usr/share/lmod/lmod/modulefiles:/easybuild/2020/modules/all";
os.environ["_ModuleTable001_"] = "X01vZHVsZVRhYmxlXz17WyJhY3RpdmVTaXplIl09MSxiYXNlTXBhdGhBPXsiL2V0Yy9sbW9kL21vZHVsZXMiLCIvdXNyL3NoYXJlL2xtb2QvbG1vZC9tb2R1bGVmaWxlcyIsIi9lYXN5YnVpbGQvMjAyMC9tb2R1bGVzL2FsbCIsfSxbImNfcmVidWlsZFRpbWUiXT03MjAwLFsiY19zaG9ydFRpbWUiXT0wLjEwNjc1MTIwMzUzNjk5LGZhbWlseT17fSxpbmFjdGl2ZT17fSxtVD17RWFzeUJ1aWxkPXtbIkZOIl09Ii9lYXN5YnVpbGQvMjAyMC9tb2R1bGVzL2FsbC9FYXN5QnVpbGQvNC40LjAubHVhIixbImRlZmF1bHQiXT0xLFsiZnVsbE5hbWUiXT0iRWFzeUJ1aWxkLzQuNC4wIixbImxvYWRPcmRlciJdPTEscHJvcFQ9e30sWyJzaG9ydCJdPSJFYXN5QnVpbGQiLFsic3RhdHVzIl09";
os.environ["_ModuleTable002_"] = "ImFjdGl2ZSIsfSx9LG1wYXRoQT17Ii9ldGMvbG1vZC9tb2R1bGVzIiwiL3Vzci9zaGFyZS9sbW9kL2xtb2QvbW9kdWxlZmlsZXMiLCIvZWFzeWJ1aWxkLzIwMjAvbW9kdWxlcy9hbGwiLH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iL2V0Yy9sbW9kL21vZHVsZXM6L3Vzci9zaGFyZS9sbW9kL2xtb2QvbW9kdWxlZmlsZXM6L2Vhc3lidWlsZC8yMDIwL21vZHVsZXMvYWxsIixbInZlcnNpb24iXT0yLH0=";
os.environ["_ModuleTable_Sz_"] = "2";
strube1@haicluster:/media/ssd/strube1$ echo $?
0
```

**Comment by bedroge** [comment]
I just ran into the same issue on my Ubuntu workstation:
```
$ ml purge
$ ml EasyBuild
$ eb --install-latest-eb-release
== Temporary log file in case of crash /data/eb/tmp/eb-o1xlhdfr/easybuild-htt3h8a9.log

WARNING: Deprecated functionality, will no longer work in v5.0: Support for Lmod version < 7.0.0 is deprecated, found version 6.6; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== found valid index for /data/apps/software/EasyBuild/4.5.0/easybuild/easyconfigs, so using it...

WARNING: Deprecated functionality, will no longer work in v5.0: Use of 'dummy' toolchain is deprecated, use 'system' toolchain instead; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== processing EasyBuild easyconfig 
/data/eb/tmp/eb-o1xlhdfr/tmp22mtp297/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.1.eb
== building and installing EasyBuild/4.5.1...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== ... (took 3 secs)
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /data/eb/build/EasyBuild/4.5.1/dummy-dummy): build failed (first 300 chars): 
Module command '/usr/share/lmod/lmod/libexec/lmod python --terse list' failed with exit code 1; stderr: Lmod has detected the following 
error: MODULEPATH has changed: run "module
update" to repair.



; stdout: false
 (took 5 secs)
== Results of the build can be found in the log file(s) /data/eb/tmp/eb-o1xlhdfr/easybuild-EasyBuild-4.5.1-20211216.225920.VdwtE.log

ERROR: Build of /data/eb/tmp/eb-o1xlhdfr/tmp22mtp297/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.5.1.eb failed (err: 'build failed (first 300 chars): Module command \'/usr/share/lmod/lmod/libexec/lmod python --terse list\' failed with exit code 1; stderr: Lmod has detected the following error: MODULEPATH has changed: run "module\nupdate" to repair.\n\n\n\n; stdout: false\n')

```

**Comment by surak** [comment]
I made the latest LMOD for Debian and ubuntu, and I’m on the process to become the official maintainer for it. I can hand you the upgraded package if you want

**Comment by bedroge** [comment]
Yes, please :-)
(though I've worked around the issue for now by creating the modulefile manually, but it would be nice to have a more recent Lmod anyway)

**Comment by boegel** [comment]
Officially support for Lmod 6.x is deprecated in EasyBuild, see https://github.com/easybuilders/easybuild-framework/pull/3077.
The most recent release of Lmod 6.x was in Nov'16...

**Comment by surak** [comment]
@bedroge have a look here. I had it fine with 8.5.25, and I simply updated to 2.6.1, so this is untested other than installing it on a clean system.

**Comment by surak** [comment]
Any suggestions on how to improve this thing is more than welcome. To be honest, I am quite new on this container stuff, and there's some manual work involved. I would like to automate the whole process eventually.

**Comment by bedroge** [comment]
@surak thanks! Seems to work fine:
```
$ module --version

Modules based on Lua: Version 8.6.1 (8.6.1-8-g047a3f13) 2021-12-10 14:46 -06:00
    by Robert McLay mclay@tacc.utexas.edu
```

Also removed my EB 4.5.1 installation and tried `eb --install-latest-eb-release` again, and that also works fine now!

**Comment by Micket** [comment]
Looks like this was long since resolved, and lmod 6 is long since dead. Closing.
