### ISSUE TITLE
Migrating from EasyBuild on python2 to python3 

### ISSUE THREAD

**Issue by nortex** [easybuilders/easybuild-framework#3846]
Hi,

So far we are using easybuild that was built with /usr/bin/python which is Python-2.7.5 version.

How can we migrate to EasyBuild under python 3.7 without braking the current installation? Usually we upgrade EB using the command:

eb --install-latest-eb-release

How can we instruct easybuild to use python3 instead of python2.7 ?

**Comment by ocaisa** [comment]
See https://docs.easybuild.io/en/latest/Installation.html#setting-eb-python

If you want to configure it such that EB will use Python 3 from now on use:
```
EB_PYTHON=python3.6 eb --install-latest-eb-release
```
which will use python3 and configure the resulting module file such that it will use python3 by default.

**Comment by nortex** [comment]
> See https://docs.easybuild.io/en/latest/Installation.html#setting-eb-python
> 
> If you want to configure it such that EB will use Python 3 from now on use:
> 
> ```
> EB_PYTHON=python3.6 eb --install-latest-eb-release
> ```
> 
> which will use python3 and configure the resulting module file such that it will use python3 by default.

Thanks, when i test changing this variable, i get this message:

`[easybd@access4 ~]$ export EB_PYTHON=python3.7
[easybd@access4 ~]$ eb --version
>> Considering 'python3.7'...
>> 'python3.7' version: 3.7.0, which matches Python 3 version requirement (>= 3.5)
>> 'python3.7' is NOT able to import 'easybuild.main', so NOT retaining it
>> Considering '/usr/bin/python'...
>> '/usr/bin/python' version: 2.7.5, which matches Python 2 version requirement (>= 2.6)
>> '/usr/bin/python' is able to import 'easybuild.main', so retaining it
>> Selected Python command: /usr/bin/python (/usr/bin/python)
>> /usr/bin/python -m easybuild.main --version
/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:47: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptog
raphy, and will be removed in the next release.
  from cryptography import x509
This is EasyBuild 4.4.2 (framework: 4.4.2, easyblocks: 4.4.2)`

**Comment by ocaisa** [comment]
Interesting, with the EasyBuild module loaded what happens when you do:
```
python3.6 -c "import easybuild.main"
```

**Comment by nortex** [comment]
> Interesting, with the EasyBuild module loaded what happens when you do:
> 
> ```
> python3.7 -c "import easybuild.main"
> ```

So, when trying with python 3.7 - it fail, when trying with python3.6 it works:

`$ python3.7 -c "import easybuild.main"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/main.py", line 46, in <module>
    from easybuild.tools.build_log import EasyBuildError, print_error, print_msg, stop_logging
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/tools/build_log.py", line 42, in <module>
    from easybuild.base import fancylogger
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/base/fancylogger.py", line 88, in <module>
    from easybuild.tools.py2vs3 import raise_with_traceback, string_type
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/tools/py2vs3/__init__.py", line 29, in <module>
    from easybuild.tools.py2vs3.py3 import *  # noqa
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/tools/py2vs3/py3.py", line 45, in <module>
    from urllib.request import HTTPError, HTTPSHandler, Request, URLError, build_opener, urlopen  # noqa
ImportError: cannot import name 'HTTPSHandler' from 'urllib.request' (/usr/local/lib/python3.7/urllib/request.py)
$ python3.6 -c "import easybuild.main"
$`

So i tried to install easybuild with: 

EB_PYTHON=python3.6 eb --install-latest-eb-release

And got an error:

== 2021-09-23 11:33:53,378 easyblock.py:3701 WARNING build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2


(i removed the 4.2.2 module and 4.2.2 folder under easybuild/software/EasyBuild)

**Comment by ocaisa** [comment]
Ok, your python3.7 installation isn't built with SSL support.

Try using
```
export EB_PYTHON=3.6
eb --install-latest-eb-release
```
I suspect the envvar is not being picked up in a subshell or something

**Comment by nortex** [comment]
> Ok, your python3.7 installation isn't built with SSL support (I think).
> 
> Try using
> 
> ```
> export EB_PYTHON=3.6
> eb --install-latest-eb-release
> ```
> 
> I suspect the envvar is not being picked up in a subshell or something

Tried:

```
$ export EB_PYTHON=3.6
$ eb --install-latest-eb-release
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:47: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/main.py", line 557, in <module>
    main()
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/main.py", line 205, in main
    init_session_state = session_state()
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/tools/testing.py", line 137, in session_state
    'system_info': get_system_info(),
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/tools/systemtools.py", line 937, in get_system_info
    'gcc_version': get_tool_version('gcc', version_option='-v'),
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/tools/systemtools.py", line 731, in get_tool_version
    trace=False, stream_output=False)
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/tools/run.py", line 88, in cache_aware_func
    res = func(cmd, *args, **kwargs)
  File "/apps/easybd/easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/tools/run.py", line 149, in run_cmd
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
```

**Comment by ocaisa** [comment]
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```
I think you are sitting inside a stale file handle (probably inside the place eb wants to install), just `cd $HOME` or wherever.

**Comment by nortex** [comment]
> Ok, your python3.7 installation isn't built with SSL support (I think).
> 
> Try using
> 
> ```
> export EB_PYTHON=3.6
> eb --install-latest-eb-release
> ```
> 
> I suspect the envvar is not being picked up in a subshell or something

It worked! Thanks!

**Comment by ocaisa** [comment]
Great, closing!

**Comment by nortex** [comment]
> Great, closing!

**Comment by ocaisa** [comment]
Did you load the new module? It will only work with 4.4.2 onwards

**Comment by nortex** [comment]
> Did you load the new module? It will only work with 4.4.2 onwards

Yes, 

$ module list

Currently Loaded Modules:
  1) EasyBuild/4.4.2

**Comment by ocaisa** [comment]
Can you do `module show EasyBuild/4.4.2`?

**Comment by nortex** [comment]
> Can you do `module show EasyBuild/4.4.2`?


```
$ module show EasyBuild/4.4.2
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   /apps/easybd/easybuild/modules/all/EasyBuild/4.4.2.lua:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
help([[
Description
===========
EasyBuild is a software build and installation framework
 written in Python that allows you to install software in a structured,
 repeatable and robust way.


More information
================
 - Homepage: https://easybuilders.github.io/easybuild
]])
whatis("Description: EasyBuild is a software build and installation framework
 written in Python that allows you to install software in a structured,
 repeatable and robust way.")
whatis("Homepage: https://easybuilders.github.io/easybuild")
whatis("URL: https://easybuilders.github.io/easybuild")
conflict("EasyBuild")
prepend_path("CMAKE_PREFIX_PATH","/apps/easybd/easybuild/software/EasyBuild/4.4.2")
prepend_path("PATH","/apps/easybd/easybuild/software/EasyBuild/4.4.2/bin")
setenv("EBROOTEASYBUILD","/apps/easybd/easybuild/software/EasyBuild/4.4.2")
setenv("EBVERSIONEASYBUILD","4.4.2")
setenv("EBDEVELEASYBUILD","/apps/easybd/easybuild/software/EasyBuild/4.4.2/easybuild/EasyBuild-4.4.2-easybuild-devel")
prepend_path("PYTHONPATH","/apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python2.7/site-packages")
setenv("EB_INSTALLPYTHON","/usr/bin/python")
```

**Comment by ocaisa** [comment]
Annoying, something is going wrong in the installation, `EB_INSTALLPYTHON` should be set to the python3.6 path. Are you sure that is the module you just installed (what's the timestamp on `/apps/easybd/easybuild/modules/all/EasyBuild/4.4.2.lua`)?

**Comment by nortex** [comment]
> Annoying, something is going wrong in the installation, `EB_INSTALLPYTHON` should be set to the python3.6 path. Are you sure that is the module you just installed (what's the timestamp on `/apps/easybd/easybuild/modules/all/EasyBuild/4.4.2.lua`)?

Yes, it is new installation:

-rw-rw-r--   1 easybd testing-wx-grp 1.1K Sep 23 11:55 4.4.2.lua

**Comment by ocaisa** [comment]
Just to verify that it's not something else. Can you do:
```
# Delete the old module (so it appears to EB it is not installed)
rm /apps/easybd/easybuild/modules/all/EasyBuild/4.4.2.lua
# Load an (older) eb version
module load EasyBuild/4.4.1
export EB_PYTHON=3.6
eb --install-latest-eb-release
module load EasyBuild/4.4.2
eb --version
```

**Comment by ocaisa** [comment]
Ah, there was a typo in my instructions before: it should have been `EB_PYTHON=python3.6` (corrected already above)

**Comment by nortex** [comment]
> Ah, there was a typo in my instructions before: it should have been `EB_PYTHON=python3.6` (corrected already above)

Done, again failing with:

```
$ export EB_PYTHON=python3.6
$ eb --install-latest-eb-release
== Temporary log file in case of crash /apps/easybd/easybuild/temp/easybuild-8b7fbn3j.log

WARNING: Found one or more non-allowed loaded (EasyBuild-generated) modules in current environment:
* EasyBuild/4.4.1

This is not recommended since it may affect the installation procedure(s) performed by EasyBuild.

To make EasyBuild allow particular loaded modules, use the --allow-loaded-modules configuration option.
To specify action to take when loaded modules are detected, use --detect-loaded-modules={error,ignore,purge,unload,warn}.

See http://easybuild.readthedocs.io/en/latest/Detecting_loaded_modules.html for more information.

== found valid index for /apps/easybd/easybuild/software/EasyBuild/4.4.1/easybuild/easyconfigs, so using it...

WARNING: Deprecated functionality, will no longer work in v5.0: Use of 'dummy' toolchain is deprecated, use 'system' toolchain instead; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== processing EasyBuild easyconfig /apps/easybd/easybuild/temp/eb-vdvj2q66/tmpveyooh7j/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.2.eb
== building and installing EasyBuild/4.4.2...
== fetching files...
== creating build dir, resetting environment...
== ... (took 9 secs)
== unpacking...
== ... (took 4 secs)
== patching...
== preparing...
== ... (took 1 secs)
== configuring...
== building...
== testing...
== installing...
== ... (took 39 secs)
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== ... (took 6 secs)
== FAILED: Installation ended unsuccessfully (build directory: /apps/easybd/easybuild/build/EasyBuild/4.4.2/dummy-dummy): build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2 (took 1 min 1 secs)
== Results of the build can be found in the log file(s) /apps/easybd/easybuild/temp/easybuild-EasyBuild-4.4.2-20210923.121122.NdUlI.log
ERROR: Build of /apps/easybd/easybuild/temp/eb-vdvj2q66/tmpveyooh7j/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.2.eb failed (err: "build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2")
```

**Comment by ocaisa** [comment]
I don't know, you'll have to check the log file `/apps/easybd/easybuild/temp/easybuild-EasyBuild-4.4.2-20210923.121122.NdUlI.log` and maybe search for `3.7` to see if you can find some hints about what is going on.

**Comment by ocaisa** [comment]
It could be a problem in the easyblock where it is not respecting `EB_PYTHON` for some reason. If that is the case you can also set
```
export EB_INSTALLPYTHON=python3.6
```
and see if that helps

**Comment by nortex** [comment]
> export EB_INSTALLPYTHON=python3.6

Tried already. From log i see it is from beginning trying to set up easybuild with 3.7 and failing on sanity check

**Comment by ocaisa** [comment]
I really don't know. Would have to see the logs to understand why it's not respecting your choice.

**Comment by nortex** [comment]
> I really don't know. Would have to see the logs to understand why it's not respecting your choice.

```
$ cat /apps/easybd/easybuild/temp/easybuild-EasyBuild-4.4.2-20210923.121122.NdUlI.log | grep 3.6
== 2021-09-23 12:12:19,897 environment.py:91 INFO Environment variable EBVERSIONPYTHON set to 3.6.8 (previously undefined)
== 2021-09-23 12:12:19,898 easyblock.py:2832 INFO Using (only) sanity check paths specified by easyconfig file: {'files': ['bin/eb'], 'dirs': ['lib/python3.6/site-packages']}
== 2021-09-23 12:12:19,899 easyblock.py:3046 INFO (non-empty) directory not found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2, consider fallback locations: 'lib64/python3.6/site-packages'
== 2021-09-23 12:12:19,899 easyblock.py:3052 WARNING Sanity check: no (non-empty) directory found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2
== 2021-09-23 12:12:23,553 environment.py:91 INFO Environment variable EBVERSIONPYTHON set to 3.6.8 (previously undefined)
== 2021-09-23 12:12:23,701 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/base/exceptions.py:124 in __init__): Sanity check failed: no (non-empty) directory found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2 (at easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py:3117 in _sanity_check_step)
== 2021-09-23 12:12:23,704 easyblock.py:3701 WARNING build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2
```

```
$ cat /apps/easybd/easybuild/temp/easybuild-EasyBuild-4.4.2-20210923.121122.NdUlI.log | grep 3.7
Writing /apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages/easybuild_easyconfigs-4.4.2-py3.7.egg-info
/usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'
== 2021-09-23 12:12:17,552 environment.py:91 INFO Environment variable PYTHONPATH set to /apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages (previous value: '/apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages:/apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages')
prepend_path("PYTHONPATH", pathJoin(root, "lib/python3.7/site-packages"))
== 2021-09-23 12:12:19,897 environment.py:91 INFO Environment variable PYTHONPATH set to /apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages (previously undefined)
prepend_path("PYTHONPATH", pathJoin(root, "lib/python3.7/site-packages"))
== 2021-09-23 12:12:23,553 environment.py:91 INFO Environment variable PYTHONPATH set to /apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages (previously undefined)
== 2021-09-23 12:12:23,701 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/base/exceptions.py:124 in __init__): Sanity check failed: no (non-empty) directory found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2 (at easybuild/software/EasyBuild/4.4.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py:3117 in _sanity_check_step)
== 2021-09-23 12:12:23,701 build_log.py:265 INFO ... (took 6 secs)
== 2021-09-23 12:12:23,702 filetools.py:1876 INFO Removing lock /apps/easybd/easybuild/software/.locks/_apps_easybd_easybuild_software_EasyBuild_4.4.2.lock...
== 2021-09-23 12:12:23,704 filetools.py:358 INFO Path /apps/easybd/easybuild/software/.locks/_apps_easybd_easybuild_software_EasyBuild_4.4.2.lock successfully removed.
== 2021-09-23 12:12:23,704 filetools.py:1880 INFO Lock removed: /apps/easybd/easybuild/software/.locks/_apps_easybd_easybuild_software_EasyBuild_4.4.2.lock
== 2021-09-23 12:12:23,704 easyblock.py:3701 WARNING build failed (first 300 chars): Sanity check failed: no (non-empty) directory found at 'lib/python3.6/site-packages' in /apps/easybd/easybuild/software/EasyBuild/4.4.2
== 2021-09-23 12:12:23,704 easyblock.py:302 INFO Closing log for application name EasyBuild version 4.4.2


```

**Comment by nortex** [comment]
I guess this is our problem:

```
== 2021-09-23 12:11:38,399 pythonpackage.py:601 INFO Checking of $LDSHARED auto-enabled for sufficiently recent Python version 3.7.0
== 2021-09-23 12:11:50,345 filetools.py:1775 INFO Creating directory /apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages (parents: True, set_gid: False, sticky: False)
== 2021-09-23 12:11:50,345 environment.py:91 INFO Environment variable PYTHONPATH set to /apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages (previously undefined)
```

**Comment by nortex** [comment]
> I guess this is our problem:
> 
> ```
> == 2021-09-23 12:11:38,399 pythonpackage.py:601 INFO Checking of $LDSHARED auto-enabled for sufficiently recent Python version 3.7.0
> == 2021-09-23 12:11:50,345 filetools.py:1775 INFO Creating directory /apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages (parents: True, set_gid: False, sticky: False)
> == 2021-09-23 12:11:50,345 environment.py:91 INFO Environment variable PYTHONPATH set to /apps/easybd/easybuild/software/EasyBuild/4.4.2/lib/python3.7/site-packages (previously undefined)
> ```

$ python3 --version
Python 3.7.0

**Comment by nortex** [comment]
It is using binary python3 instead of python 3.6:
```

$ cat /apps/easybd/easybuild/temp/easybuild-EasyBuild-4.4.2-20210923.121122.NdUlI.log | grep "python3 "
== 2021-09-23 12:11:38,257 filetools.py:498 INFO Command python3 found at /usr/local/bin/python3
== 2021-09-23 12:11:38,258 run.py:233 INFO running cmd: python3 -c 'import sys; print("%s.%s.%s" % sys.version_info[:3])'
== 2021-09-23 12:11:38,288 filetools.py:498 INFO Command python3 found at /usr/local/bin/python3
== 2021-09-23 12:11:38,288 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib(plat_specific=False, prefix="/tmp/"))'
== 2021-09-23 12:11:38,327 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib(plat_specific=True, prefix="/tmp/"))'
== 2021-09-23 12:11:38,367 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import sys; print("%s.%s.%s" % sys.version_info[:3])'
== 2021-09-23 12:11:38,402 run.py:233 INFO running cmd: /usr/local/bin/python3 -V
== 2021-09-23 12:11:38,415 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import sys; print(sys.executable)'
== 2021-09-23 12:11:38,452 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import sys; print(sys.path)'
== 2021-09-23 12:11:50,346 run.py:233 INFO running cmd:  /usr/local/bin/python3 setup.py install --prefix=/apps/easybd/easybuild/software/EasyBuild/4.4.2
== 2021-09-23 12:11:53,071 run.py:582 INFO cmd " /usr/local/bin/python3 setup.py install --prefix=/apps/easybd/easybuild/software/EasyBuild/4.4.2 " exited with exit code 0 and output:
/usr/local/bin/python3 /apps/easybd/easybuild/temp/eb-vdvj2q66/tmpqjlnhwm3.py
== 2021-09-23 12:11:53,099 run.py:233 INFO running cmd:  /usr/local/bin/python3 setup.py install --prefix=/apps/easybd/easybuild/software/EasyBuild/4.4.2
== 2021-09-23 12:11:54,489 run.py:582 INFO cmd " /usr/local/bin/python3 setup.py install --prefix=/apps/easybd/easybuild/software/EasyBuild/4.4.2 " exited with exit code 0 and output:
== 2021-09-23 12:11:54,502 run.py:233 INFO running cmd:  /usr/local/bin/python3 setup.py install --prefix=/apps/easybd/easybuild/software/EasyBuild/4.4.2
== 2021-09-23 12:12:17,335 run.py:582 INFO cmd " /usr/local/bin/python3 setup.py install --prefix=/apps/easybd/easybuild/software/EasyBuild/4.4.2 " exited with exit code 0 and output:
== 2021-09-23 12:12:17,746 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib(plat_specific=False, prefix="/tmp/"))'
== 2021-09-23 12:12:17,787 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib(plat_specific=True, prefix="/tmp/"))'
== 2021-09-23 12:12:19,764 run.py:233 INFO running cmd: /usr/local/bin/python3 -c "import easybuild"
== 2021-09-23 12:12:19,995 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib(plat_specific=False, prefix="/tmp/"))'
== 2021-09-23 12:12:20,040 run.py:233 INFO running cmd: /usr/local/bin/python3 -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib(plat_specific=True, prefix="/tmp/"))'
```

**Comment by ocaisa** [comment]
Can you try again with `EB_VERBOSE=1` and also look for `Python command being used` in the output/log

**Comment by nortex** [comment]
> Can you try again with `EB_VERBOSE=1` and also look for `Python command being used` in the output/log

$ EB_VERBOSE=1 eb --install-latest-eb-release
>> Considering 'python3.6'...
>> 'python3.6' version: 3.6.8, which matches Python 3 version requirement (>= 3.5)
>> 'python3.6' is able to import 'easybuild.main', so retaining it
>> Selected Python command: python3.6 (/usr/bin/python3.6)
>> python3.6 -m easybuild.main --install-latest-eb-release
== Temporary log file in case of crash /apps/easybd/easybuild/temp/easybuild-h_zqgkzr.log

**Comment by nortex** [comment]
> > Can you try again with `EB_VERBOSE=1` and also look for `Python command being used` in the output/log
> 
> $ EB_VERBOSE=1 eb --install-latest-eb-release
> 
> > > Considering 'python3.6'...
> > > 'python3.6' version: 3.6.8, which matches Python 3 version requirement (>= 3.5)
> > > 'python3.6' is able to import 'easybuild.main', so retaining it
> > > Selected Python command: python3.6 (/usr/bin/python3.6)
> > > python3.6 -m easybuild.main --install-latest-eb-release
> > > == Temporary log file in case of crash /apps/easybd/easybuild/temp/easybuild-h_zqgkzr.log

But during easybuild installation itself - it is using the python3 binary instead of python 3.6

**Comment by nortex** [comment]
Ok i was able to install it. I removed the /usr/local/bin from the $PATH and it finished successfully.

I guess this should be fixed in the next release as it looks like easybuild is using python3 binary instead of actual python version that was specified.

**Comment by ocaisa** [comment]
Yeah, I am looking into this now

**Comment by ocaisa** [comment]
With this fix:
```
[EESSI pilot 2021.03] $ python --version
Python 3.8.9

[EESSI pilot 2021.03] $ EB_VERBOSE=1 EB_PYTHON=/cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/Python/3.8.2-GCCcore-9.3.0/bin/python eb --install-latest
>> Considering '/cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/Python/3.8.2-GCCcore-9.3.0/bin/python'...
>> '/cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/Python/3.8.2-GCCcore-9.3.0/bin/python' version: 3.8.2, which matches Python 3 version requirement (>= 3.5)
>> '/cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/Python/3.8.2-GCCcore-9.3.0/bin/python' is able to import 'easybuild.main', so retaining it
>> Selected Python command: /cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/Python/3.8.2-GCCcore-9.3.0/bin/python (/cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/Python/3.8.2-GCCcore-9.3.0/bin/python)
>> /cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/Python/3.8.2-GCCcore-9.3.0/bin/python -m easybuild.main --install-latest
== Temporary log file in case of crash /tmp/eb-j7k41fuu/easybuild-tokt0l3s.log

WARNING: Deprecated functionality, will no longer work in v5.0: Use of 'dummy' toolchain is deprecated, use 'system' toolchain instead; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== processing EasyBuild easyconfig /tmp/eb-j7k41fuu/tmp8bvcd9hd/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.4.2.eb
== building and installing Core/EasyBuild/4.4.2...
== fetching files...
== ... (took 2 secs)
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== ... (took 8 secs)
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== ... (took 9 secs)
== cleaning up...
== creating module...
== ... (took 1 secs)
== permissions...
== ... (took 2 secs)
== packaging...
== COMPLETED: Installation ended successfully (took 26 secs)
== Results of the build can be found in the log file(s) /home/alanc/.local/easybuild/software/EasyBuild/4.4.2/easybuild/easybuild-EasyBuild-4.4.2-20210923.105753.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /tmp/eb-j7k41fuu/easybuild-tokt0l3s.log* have been removed.
== Temporary directory /tmp/eb-j7k41fuu has been removed.

[EESSI pilot 2021.03] $ module show EasyBuild/4.4.2 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   /home/alanc/.local/easybuild/modules/all/Core/EasyBuild/4.4.2.lua:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
help([[
Description
===========
EasyBuild is a software build and installation framework
 written in Python that allows you to install software in a structured,
 repeatable and robust way.


More information
================
 - Homepage: https://easybuilders.github.io/easybuild
]])
whatis("Description: EasyBuild is a software build and installation framework
 written in Python that allows you to install software in a structured,
 repeatable and robust way.")
whatis("Homepage: https://easybuilders.github.io/easybuild")
whatis("URL: https://easybuilders.github.io/easybuild")
conflict("EasyBuild")
prepend_path("CMAKE_PREFIX_PATH","/home/alanc/.local/easybuild/software/EasyBuild/4.4.2")
prepend_path("PATH","/home/alanc/.local/easybuild/software/EasyBuild/4.4.2/bin")
setenv("EBROOTEASYBUILD","/home/alanc/.local/easybuild/software/EasyBuild/4.4.2")
setenv("EBVERSIONEASYBUILD","4.4.2")
setenv("EBDEVELEASYBUILD","/home/alanc/.local/easybuild/software/EasyBuild/4.4.2/easybuild/Core-EasyBuild-4.4.2-easybuild-devel")
prepend_path("PYTHONPATH","/home/alanc/.local/easybuild/software/EasyBuild/4.4.2/lib/python3.8/site-packages")
setenv("EB_INSTALLPYTHON","/cvmfs/pilot.eessi-hpc.org/2021.03/software/linux/x86_64/generic/software/Python/3.8.2-GCCcore-9.3.0/bin/python")
```

**Comment by ocaisa** [comment]
Reproduced and fixed in easybuilders/easybuild-easyblocks#2581

**Comment by nortex** [comment]
Hi,

Was upgrading now from 4.4.2 to 4.5.0 - and still got into same error. 

Was fixed , again, by removing the python3.7 from path.

**Comment by ocaisa** [comment]
Yes, unfortunately that's to be expected, the changes to the easyblock are in the latest release, they will only kick in when you install EB with that version (or later)

**Comment by ocaisa** [comment]
You can also use `--include-easyblocks-from-pr=2581` which will also pull in the necessary changes
