### ISSUE TITLE
Failed to remove file /tmp/fake_vsc_zn4q3y6n: [Errno 21] Is a directory:

### ISSUE THREAD

**Issue by Yogesh04793** [easybuilders/easybuild-framework#4222]
== 2023-03-07 08:01:42,100 build_log.py:227 INFO This is EasyBuild 4.4.1 (framework: 4.4.1, easyblocks: 4.4.1) on host ip-10-161-0-149.
== 2023-03-07 08:01:42,100 build_log.py:230 INFO Command line: --buildpath='/mnt/building/build' --robot --tmpdir='/mnt/building/tmp' SAMtools-1.12-GCC-10.3.0.eb
== 2023-03-07 08:01:42,100 build_log.py:232 INFO Using /tmp as temporary directory
== 2023-03-07 08:01:42,100 robot.py:58 INFO Using robot path(s): []
== 2023-03-07 08:01:42,101 options.py:1677 INFO Using default external modules metadata cfg files: ['/apps/.local/easybuild/software/EasyBuild/4.4.1/etc/cray_external_modules_metadata.cfg', '/apps/.local/easybuild/software/EasyBuild/4.4.1/etc/ohpc_external_modules_metadata.cfg']
== 2023-03-07 08:01:42,112 systemtools.py:1032 INFO Found Python version 3.7
== 2023-03-07 08:01:42,112 systemtools.py:1044 INFO Running EasyBuild with Python 3 (version 3.7)
== 2023-03-07 08:01:42,152 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/4.4.1/lib/python3.6/site-packages/easybuild/base/exceptions.py:124 in __init__): Failed to remove file /tmp/fake_vsc_zn4q3y6n: [Errno 21] Is a directory: '/tmp/fake_vsc_zn4q3y6n' (at easybuild/software/EasyBuild/4.4.1/lib/python3.6/site-packages/easybuild/tools/filetools.py:331 in remove_file)

**Comment by boegel** [comment]
@Yogesh04793 Are you also seeing this with a more recent version of EasyBuild?

This may be a problem that we have fixed already...
