### PR TITLE
fix crash in dep_graph when easyconfig that uses multi_deps is used

### PR DESCRIPTION
**Pull request by boegel**
Fix for another problem caused by #2813 (similar to problem fixed in #2826):

```
Traceback (most recent call last):
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 130, in test_dep_graph
    dep_graph(fn, self.ordered_specs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/easybuild_framework-3.9.0.dev0-py2.6.egg/easybuild/framework/easyconfig/tools.py", line 200, in dep_graph
    spec['ec'].build_dependencies = [mk_node_name(s) for s in spec['ec']['builddependencies']]
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/easybuild_framework-3.9.0.dev0-py2.6.egg/easybuild/framework/easyconfig/tools.py", line 182, in mk_node_name
    if spec.get('external_module', False):
AttributeError: 'list' object has no attribute 'get'
```

### CODE REVIEW

**Comment by akesandgren** [comment]
Going in, thanks @boegel!
