### PR TITLE
improve trace output for executed commands + drop requirement for --experimental for --trace

### PR DESCRIPTION
**Pull request by boegel**
Example output with EasyBuild v3.4.0:

```
== configuring...
  >> running command './configure --prefix=/Users/kehoste/.local/easybuild/software/zlib/1.2.11' (output in /tmp/eb-508__5/easybuild-run_cmd-GQnYWm.log) [started at: 2017-09-15 20:58:04]
== building...
  >> running command 'make -j 4 CFLAGS="-O2 -fPIC"' (output in /tmp/eb-508__5/easybuild-run_cmd-NXCfvW.log) [started at: 2017-09-15 20:58:05]
```

Example output with this patch included:

```
== configuring...
  >> running command:
	[started at: 2017-09-15 20:56:14]
	[output logged in /tmp/eb-c13cXN/easybuild-run_cmd-pV_hJa.log]
	./configure --prefix=/Users/kehoste/.local/easybuild/software/zlib/1.2.11
  >> command completed: exit 0, ran in 1s
== building...
  >> running command:
	[started at: 2017-09-15 20:56:15]
	[output logged in /tmp/eb-c13cXN/easybuild-run_cmd-i0AnOq.log]
	make -j 4 CFLAGS="-O2 -fPIC"
  >> command completed: exit 0, ran in 3s
```

### CODE REVIEW

File: easybuild/tools/build_log.py [hunk 1]
```diff
@@ -299,3 +300,34 @@ def print_warning(message, silent=False):
...
+    Return string representing amount of time that has passed since specified timestamp
+
+    :param start_time: datetime value representing start time
+    :return: string value representing amount of time passed since start_time;
+             format: "[[%d hours, ]%d mins, ]%d sec(s)"
+    """
+    tot_time = datetime.now() - start_time
+    if tot_time.seconds > 0:
+        hours, mins, secs = 0, 0, tot_time.seconds
+        if secs >= 60:
```
Comment (wpoely86) [inline easybuild/tools/build_log.py]: this can be done better I hope? Take total_seconds, use it as timestamp input and use the buildin formatting functions?

Comment (boegel) [reply easybuild/tools/build_log.py]: fixed, but apparently this doesn't work with Python 2.6... :(

```
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'
```
